# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive\python\laptop_charging_animation\animation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_animation(object):
    def setupUi(self, animation):
        animation.setObjectName("animation")
        animation.resize(400, 300)

        self.retranslateUi(animation)
        QtCore.QMetaObject.connectSlotsByName(animation)

    def retranslateUi(self, animation):
        _translate = QtCore.QCoreApplication.translate
        animation.setWindowTitle(_translate("animation", "animation"))
